### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jansengsy**

### CODE REVIEW

**Comment by Jimbo4794** [comment]
approve

**Comment by Jimbo4794** [comment]
approved

**Comment by Jimbo4794** [comment]
rebuild

**Comment by cicsdeliverytest** [comment]
Can a repo admin please check this commit anmd comment %s to prcoeed to build.

**Comment by Jimbo4794** [comment]
lol typos

**Comment by cicsdeliverytest** [comment]
Can a repo admin please check this commit and comment approved to prcoeed to build.

**Comment by Jimbo4794** [comment]
approved

**Comment by Jimbo4794** [comment]
approved

**Pull request closed without merging**
